#!/bin/bash

echo "🔍 GitHub Pages Deployment Checker"
echo "=================================="
echo ""
echo "Repository: kaushiks18/estate-pro-finder-main"
echo "Expected URL: https://kaushiks18.github.io/estate-pro-finder-main/"
echo ""
echo "🔧 Troubleshooting Steps:"
echo "1. Make sure GitHub Pages is enabled in repository settings"
echo "2. Ensure source is set to 'GitHub Actions'"
echo "3. Check that the workflow ran successfully"
echo "4. Wait 2-3 minutes for deployment to complete"
echo ""
echo "📂 File paths after deployment:"
echo "Home page: https://kaushiks18.github.io/estate-pro-finder-main/"
echo "Agent login: https://kaushiks18.github.io/estate-pro-finder-main/agent-login"
echo "Buy page: https://kaushiks18.github.io/estate-pro-finder-main/buy"
echo ""
echo "✅ If you still get 404 errors:"
echo "1. Check repository Settings > Pages"
echo "2. Verify the workflow completed in Actions tab"
echo "3. Try accessing the URLs above directly"
